import {useEffect,useRef,useState} from 'react';
import {works} from '../../data/works';
import type {GameId,RoomId} from '../world';
import type {MaturityController} from './useMaturity';
import config from './config.json';
import {Overlay} from './Overlay';
export function ReviewDesk({model,onPlay,onRoom,onStamp}:{model:MaturityController;onPlay:(id:GameId)=>void;onRoom:(room:RoomId)=>void;onStamp:()=>void}){
 const {save,change}=model;
 const [selected,setSelected]=useState(save.reading.work),[page,setPage]=useState(save.reading.page);
 const content=useRef<HTMLDivElement>(null),restored=useRef(false),fromPermit=useRef(model.view==='permit');
 const active=works.find(w=>w.id===selected);
 useEffect(()=>{if(model.view==='permit')fromPermit.current=true;if(content.current&&!restored.current){restored.current=true;content.current.scrollTop=save.reading.scroll;if(active&&save.clearance&&!fromPermit.current)model.speak('restored');}},[active,model,save.clearance,save.reading.scroll]);
 function select(id:string){setSelected(id);setPage('overview');change(s=>({...s,reading:{work:id,page:'overview',scroll:0}}));content.current?.scrollTo(0,0);}
 function turn(next:string){setPage(next);change(s=>({...s,reading:{work:selected,page:next,scroll:0}}));content.current?.scrollTo(0,0);}
 const [stamped,setStamped]=useState(false),stampTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>()=>clearTimeout(stampTimer.current),[]);
 const authorize=(skip=false)=>{if(stamped)return;onStamp();if(skip){model.grant();return;}setStamped(true);stampTimer.current=setTimeout(()=>model.grant(),700);};
 if(model.view==='permit')return <Overlay label="特聘调阅公函" onClose={model.close} className="permit-overlay"><div className="clearance-document"><small>VISITOR SERVICES · MW / 001</small><h2>特聘调阅公函</h2><p className="letter-salutation">致来到灯下的访客：</p><p>此函准予调阅工作区内公开的项目资料、制作记录与复盘。无需填写姓名，也不必说明来意。</p><p>做成的部分与仍在修改的部分，一并存档。</p><div className="permit-signature">工作区资料室<br/><small>私人助手代办</small></div><button className={`stamp-target ${stamped?"stamped":""}`} disabled={stamped} onClick={()=>authorize()} aria-label="盖章并开通调阅权限"><span>{stamped?"已授权调阅":"调阅授权"}</span><small>SPECIAL GUEST</small></button><button className="skip-permit" onClick={()=>authorize(true)}>跳过演出，直接查阅</button></div></Overlay>;
 const game:GameId|null=selected==='click-down'?'clickdown':selected==='anchored-gaze'?'anchored-gaze':null;
 const target=(config.workRooms as Record<string,RoomId>)[selected];
 return <Overlay label="项目调阅台" onClose={model.close} className="review-overlay"><header className="review-heading"><small>WORKING ARCHIVE / {save.clearance?'SPECIAL GUEST':'VISITOR'}</small><h2>项目调阅台</h2><p>做过什么，为什么这样做，以及留下的记录。</p>{!save.clearance&&<button onClick={()=>model.setView('permit')}>办理调阅公函 ↗</button>}</header><div className="review-columns"><nav aria-label="项目目录">{works.map((w,i)=><button key={w.id} className={selected===w.id?'selected':''} aria-current={selected===w.id?'page':undefined} onClick={()=>select(w.id)}><small>{String(i+1).padStart(2,'0')}</small>{w.shortTitle||w.title}</button>)}</nav><div className="review-content" ref={content} onScroll={e=>{const scroll=e.currentTarget.scrollTop;change(s=>({...s,reading:{work:selected,page,scroll}}));}}>{active?<><h3>{active.shortTitle||active.title}</h3><div className="review-tabs">{['overview','process','evidence'].map((p,i)=><button key={p} aria-pressed={page===p} onClick={()=>{if(p!=='overview'&&!save.clearance){model.setView('permit');return;}turn(p);}}>{['概览','设计与复盘','资料与验证'][i]}</button>)}</div>{page==='overview'?<><dl className="four-questions"><dt>这是什么？</dt><dd>{active.summary}</dd><dt>我负责什么？</dt><dd>{active.role}</dd><dt>解决什么问题？</dt><dd>{active.designQuestion||active.oneLine}</dd><dt>在哪里验证？</dt><dd className="review-links">{game&&<button onClick={()=>onPlay(game)}>在这里试玩 ↗</button>}{active.playUrl&&<a href={active.playUrl} target="_blank" rel="noreferrer">独立窗口试玩 ↗</a>}{active.download&&<a href={active.download.url}>下载作品 ↓</a>}{!game&&!active.playUrl&&!active.download&&active.links?.slice(0,1).map(l=><a key={l.url} href={l.url} target="_blank" rel="noreferrer">{l.label} ↗</a>)}</dd></dl>{active.media[0]&&<img className="review-cover" loading="lazy" src={active.media[0].poster||active.media[0].src} alt={active.media[0].caption||active.title}/>}</>:page==='process'?<><p>{active.period}</p>{active.designHighlights?.map(h=><section key={h.title}><h4>{h.title}</h4><p>{h.body}</p></section>)}<h4>具体工作</h4><ul>{active.contribution.map(c=><li key={c}>{c}</li>)}</ul></>:<><p>{active.engine}</p>{active.links?.map(l=><p key={l.url}><a href={l.url} target="_blank" rel="noreferrer">{l.label} ↗</a></p>)}{active.download&&<><a href={active.download.url}>下载：{active.download.version}</a><p>{active.download.size}</p>{active.download.sha256&&<details><summary>文件校验SHA-256</summary><code className="checksum">{active.download.sha256}</code></details>}</>}{active.proof?.map(p=><p key={p.label}><strong>{p.label}：</strong>{p.value}</p>)}</>}{save.clearance&&target&&<button className="review-room-link" onClick={()=>onRoom(target)}>去对应房间看看 ↗</button>}</>:<div className="review-welcome"><span>MW</span><h3>从一份档案开始。</h3><p>左侧是项目目录。每份档案先回答四个问题，再展开制作过程。</p><button onClick={()=>select(works[0].id)}>查看代表作品 →</button></div>}</div></div></Overlay>;
}
